<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="nesfr_arm_only" >

    <xacro:property name="M_PI" value="3.1415926535897931" />

    <xacro:property name="rgbd_cam_size_x" value="0.1" />
    <xacro:property name="rgbd_cam_size_y" value="0.2" />
    <xacro:property name="rgbd_cam_size_z" value="0.1" />

    <xacro:property name="main_cam_tilt_init_value" value="${-20* M_PI/180.0}" />
    <xacro:property name="main_cam_size_x" value="0.20" />
    <xacro:property name="main_cam_size_y" value="0.1" />
    <xacro:property name="main_cam_size_z" value="0.1" />

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="red">
        <color rgba="0.5 0 0 1" />
    </material>

    <material name="green">
        <color rgba="0 0.5 0 1" />
    </material>

    <material name="blue">
        <color rgba="0 0 0.5 1" />
    </material>

    <material name="black">
        <color rgba="0.1 0.1 0.1 1" />
    </material>

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.07131916" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 0.05" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.10" radius="0.10"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.10" radius="0.10"/>
            </geometry>
        </collision>
    </link>

    <joint name="main_cam_base_joint" type="prismatic">
        <parent link="base_link"/>
        <child link="main_cam_pan_link"/>
        <axis xyz="0 0 1" />
        <limit effort="10" velocity="1"  lower="0.0" upper="2.0" />
        <origin xyz="0.0 0.0 0.2" rpy="0 0 0"/>
    </joint>

    <!--
        Main Camera
    -->
    <link name="main_cam_pan_link">
    </link>

    <joint name="main_cam_pan_joint" type="revolute">
        <parent link="main_cam_pan_link"/>
        <child link="main_cam_tilt_link"/>
        <axis xyz="0 0 1" />
        <limit effort="10" velocity="1"  lower="-${M_PI}" upper="${M_PI}" />
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    </joint>

    <link name="main_cam_tilt_link">
    </link>

    <joint name="main_cam_tilt_joint" type="revolute">
        <parent link="main_cam_tilt_link"/>
        <child link="main_cam_link"/>
        <axis xyz="0 1 0" />
        <limit effort="10" velocity="1"  lower="-${0.5*M_PI}" upper="0.0" />
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    </joint>

    <link name="main_cam_link">
        <visual>
            <origin xyz="0.0 0.0 ${0.5*main_cam_size_z}" rpy="0 0 0"/>
            <geometry>
                <box size="${main_cam_size_x} ${main_cam_size_y} ${main_cam_size_z}" />
            </geometry>
            <material name="red"/>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${0.5*main_cam_size_z}" rpy="0 0 0"/>
            <geometry>
                <box size="${main_cam_size_x} ${main_cam_size_y} ${main_cam_size_z}" />
            </geometry>
        </collision>
    </link>

    <joint name="main_img_joint" type="fixed">
        <parent link="main_cam_link"/>
        <child link="main_img_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="-${0.5*M_PI} 0 -${0.5*M_PI}"/>
    </joint>

    <link name="main_img_link">
    </link>

</robot>
