nesfr7_arm_00/nesfr7_arm_node:
  ros__parameters:
    test: 120
    kinematics:
      shoulder:
        x: 0
        y: 0
        z: 0
        roll: 0
        pitch: 0
        yaw: 0

      upper_arm:
        x: 0
        y: 0
        z: 0
        roll: 0
        pitch: 0
        yaw: 0

      fore_arm:
        x: 0
        y: 0
        z: 0
        roll: 0
        pitch: 0
        yaw: 0
    #
    # reference: https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/foxy/ur_description/config/ur3/joint_limits.yaml
    #
    joint_limits:
      shoulder_lift:
        min_position: 0.08726 # 5.0*M_PI/180
        max_position: 1.04719 # 60.0*M_PI/180

      elbow_joint:
        min_position: 0.17453 # 10.0*M_PI/180
        max_position: 2.09439 # 120.0*M_PI/180
